// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7keNQMEt8fZ3oeAdeUfqtu0uOQ3lAdY',
    appId: '1:543285176326:web:f8edeb7699180a6ecabb87',
    messagingSenderId: '543285176326',
    projectId: 'notepad-ef44d',
    authDomain: 'notepad-ef44d.firebaseapp.com',
    storageBucket: 'notepad-ef44d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHaUTlpHwaV2uPPNyPv9OWZ71AaMDDVw',
    appId: '1:543285176326:android:221f5dbf749ea45fcabb87',
    messagingSenderId: '543285176326',
    projectId: 'notepad-ef44d',
    storageBucket: 'notepad-ef44d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWr0T_A-fCq1L97sN2qQJcPZ9ISKW9Lcg',
    appId: '1:543285176326:ios:42104a99567b8184cabb87',
    messagingSenderId: '543285176326',
    projectId: 'notepad-ef44d',
    storageBucket: 'notepad-ef44d.firebasestorage.app',
    iosClientId: '543285176326-amost4je1hkcbpgr457cg86sbhlrrjic.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureNotepad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWr0T_A-fCq1L97sN2qQJcPZ9ISKW9Lcg',
    appId: '1:543285176326:ios:42104a99567b8184cabb87',
    messagingSenderId: '543285176326',
    projectId: 'notepad-ef44d',
    storageBucket: 'notepad-ef44d.firebasestorage.app',
    iosClientId: '543285176326-amost4je1hkcbpgr457cg86sbhlrrjic.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureNotepad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7keNQMEt8fZ3oeAdeUfqtu0uOQ3lAdY',
    appId: '1:543285176326:web:b394850c7a671c44cabb87',
    messagingSenderId: '543285176326',
    projectId: 'notepad-ef44d',
    authDomain: 'notepad-ef44d.firebaseapp.com',
    storageBucket: 'notepad-ef44d.firebasestorage.app',
  );
}
